### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by 330676687** [zyyoona7/WheelPicker#41]
setSelectedDate和setMaxSelectedDate都设置为2021-01-31

> Back traces starts.
java.lang.IllegalArgumentException: maxSelectedPosition must be greater than minSelectedPosition in WheelView.
    at com.zyyoona7.wheel.WheelView.V0(WheelView.kt:18)
    at com.zyyoona7.picker.ex.WheelDayView.r1(WheelExtViews.kt:1)
    at g.y.a.c.b.g(DatePickerHelper.kt:17)
    at com.zyyoona7.wheel.WheelView.a1(WheelView.kt:12)
    at com.zyyoona7.picker.ex.WheelYearView.n1(WheelExtViews.kt:1)
    at com.zyyoona7.picker.ex.WheelYearView.o1(WheelExtViews.kt:1)
    at g.y.a.c.b.e(DatePickerHelper.kt:1)
    at g.y.a.c.b.setSelectedDate(DatePickerHelper.kt:7)
    at com.zyyoona7.picker.DatePickerView.setSelectedDate(DatePickerView.kt:2)
    at com.z.tzrl.popupview.DatePickerPopup.D(DatePickerPopup.kt:44)
    at com.lxj.xpopup.core.BasePopupView.y(BasePopupView.java:7)
    at com.lxj.xpopup.core.BasePopupView$b.run(BasePopupView.java:3)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:7142)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Back traces ends.

**Comment by zyyoona7** [comment]
升级到 2.0.5 已经修复了这个问题
